export const language=[
    {
        name:"HTML",
        backgroundColor:"#E2680F",
        color:"#F9F4DA"
    },
    {
        name:"CSS",
        backgroundColor:"#328AF1",
        color:"#F9F4DA"
    },
    {
        name:"JavaScript",
        backgroundColor:"#2ED3E9",
        color:"black"
    },
    {
        name:"React",
        backgroundColor:"#F4EB13",
        color:"black"
    },
    {
        name:"TypeScript",
        backgroundColor:"#298EC6",
        color:"#F9F4DA"
    },
    {
        name:"Node.js",
        backgroundColor:"#E2680D",
        color:"#F9F4DA"
    },
    {
        name:"Python",
        backgroundColor:"#298ED5",
        color:"#F9F4DA"
    },
    {
        name:"Ruby",
        backgroundColor:"red",
        color:"#F9F4DA"
    },
    {
        name:"Assembly",
        backgroundColor:"blue",
        color:"#F9F4DA"
    },
]